# Generated by Django 4.1.7 on 2023-03-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
